a = int(input("Masukan Nilai Pertama : "))
b = int(input("Masukan Input Kedua : "))

print("")
print("==== Artimatika Logika ====")
print("Penjumlahan dari " + str(a) + " + " + str(b) + " adalah " + str(a + b))
print("Penkurangan dari " + str(a) + " + " + str(b) + " adalah " + str(a - b))
print("Perkalian dari " + str(a) + " + " + str(b) + " adalah " + str(a * b))
print("Pembagian dari " + str(a) + " + " + str(b) + " adalah " + str(a / b))
print("Modulus dari " + str(a) + " + " + str(b) + " adalah " + str(a % b))
