print("Hello Python")
print("My Name is Igo Tegar Prambudhy")
print("I'am Student")
print("Program Study Informatics")
print("Faculty Computer Science")
print("My gender male")
print("I from Indonesia")
print("This is project first about python")
print("I Love Python")
print("Thank You")